name: 构建Android摄像头检测器APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
    
    - name: 设置JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    
    - name: 设置Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 29
        build-tools: 29.0.3
    
    - name: 缓存Gradle依赖
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: 赋予gradlew执行权限
      run: chmod +x gradlew
    
    - name: 清理项目
      run: ./gradlew clean
    
    - name: 构建Debug APK
      run: ./gradlew assembleDebug
    
    - name: 上传APK到Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: android-camera-detector-apk
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
    
    - name: 创建Release（如果是tag推送）
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Android摄像头检测器 ${{ github.ref }}
        draft: false
        prerelease: false
    
    - name: 上传APK到Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: app/build/outputs/apk/debug/app-debug.apk
        asset_name: android-camera-detector.apk
        asset_content_type: application/vnd.android.package-archive